language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive
  - sudo apt-get install -y xsltproc

script:
  - xsltproc --html tex/html_tex.xsl 01_intro.html > prova.txt
  - cd tex/ && ./maketex.sh
